### ISSUE TITLE
Некорректное отображение статусов игроков

### ISSUE THREAD

**Issue by teestudio** [xeeen/mafia#3]
При выходе из игры мертвого мафиози информация на панели становится некорректной: показывается, что в игре осталось меньше игроков, чем есть на самом деле, из-за дублирования сообщения о выходе. Возможно, работает при выходе игроков других ролей.

**Comment by oevseev** [comment]
Проблема частично решена при помощи #11 (исправлен эффект появления сдвоенного сообщения по выходе игрока из игры).

**Comment by oevseev** [comment]
Проблема решена.
